### ISSUE TITLE
Support before and after options 

### ISSUE THREAD

**Issue by 7rulnik** [relekang/micro-analytics-adapter-redis#14]
Adapter should react on before and after options like [adapter-flat-file-db](https://github.com/micro-analytics/adapter-flat-file-db/blob/master/index.js#L45).

Wanna send PR on this week.

**Comment by relekang** [comment]
Cool, I'll see if I can finish https://github.com/micro-analytics/micro-analytics-cli/pull/53 today so we have tests for it :v:
