### ISSUE TITLE
Add configuring of the redis connection

### ISSUE THREAD

**Issue by relekang** [relekang/micro-analytics-adapter-redis#4]
Environment variable `MAA_REDIS_DB_CONFIG` that contains a json string wich is parsed and sent to ioredis.

**Comment by jimthedev** [comment]
I've got this one.

**Comment by jimthedev** [comment]
I'm going to prefer a parsed JSON string but fall back to allowing a connection string if JSON parsing fails. ioredis allows a dsn like connection string which services like redislabs provides to users. Sound ok @relekang?

**Comment by relekang** [comment]
Sounds more than ok, so I merged your PR 🙂

**Comment by jimthedev** [comment]
Cool. Thank you!
